apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: gha-runner-scale-set-controller
  repo: oci://ghcr.io/actions/actions-runner-controller-charts
  version: "0.9.2"
  releaseName: arc
  valuesFile: "values.yaml"
  namespace: arc-systems
